version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./src/:/appdir/src
      - ./config/:/appdir/config
    ports:
      - "4567:4567"
    links:
      - mongodb
  mongodb:
    image: mongo:3.6
    ports:
      - "37017:27017"
